// Resource identifiers shared between Kickarse.rc and the C++ sources.
#pragma once

// Icon
#define IDI_APPICON              100

// Embedded payload (generated by tools/PackPayload.ps1)
#define IDR_PAYLOAD_DATA         101
#define IDR_PAYLOAD_MANIFEST     102

// Wizard pages
#define IDD_WELCOME              200
#define IDD_COMPONENTS           201
#define IDD_VST2DIR              202
#define IDD_INSTALLPAGE          203
#define IDD_FINISH               204

// Controls
#define IDC_STATIC                -1
#define IDC_STATIC_WELCOMETEXT    300
#define IDC_STATIC_WELCOMEICON    301
#define IDC_CHECK_VST3            302
#define IDC_CHECK_VST2            303
#define IDC_CHECK_CLAP            304
#define IDC_STATIC_VST3SUB        305
#define IDC_STATIC_VST2SUB        306
#define IDC_STATIC_CLAPSUB        307
#define IDC_EDIT_VST2DIR          308
#define IDC_BUTTON_BROWSE        309
#define IDC_STATIC_VST2LABEL      310
#define IDC_STATIC_VST2NOTE       311
#define IDC_STATIC_VST2NOTE2      317
#define IDC_PROGRESS              312
#define IDC_STATIC_STATUS         313
#define IDC_STATIC_FINISHTEXT     314
#define IDC_STATIC_FINISHTIP      315
#define IDC_STATIC_COMPONENTSHDR  316
