"""Pack the runtime assets into design/prototype/assets/embedded.js for the HTML prototype.

Browsers refuse to load fonts from file:// URLs (CORS), and the prototype must open by
double-clicking index.html. So fonts, PNGs and the wordmark path data are inlined as base64 /
JSON into one script that defines window.KICK_ASSETS. The prototype loads fonts through the
FontFace API from ArrayBuffers and images from data: URLs, which also keeps the canvas
untainted so screenshots via canvas.toDataURL() work.

Run after any asset script:  python tools/assets/embed_prototype.py
"""
from __future__ import annotations

import base64
import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parents[2]
FONTS = ROOT / "resources" / "fonts"
IMAGES = ROOT / "resources" / "images"
OUT = ROOT / "design" / "prototype" / "assets" / "embedded.js"

FONT_FILES = {
    "KickSC-Medium": "ArchivoSC-Medium.ttf",
    "KickSC-SemiBold": "ArchivoSC-SemiBold.ttf",
    "KickExp-SemiBold": "ArchivoExp-SemiBold.ttf",
}
IMAGE_FILES = {
    "knobHero": "knob_hero@2x.png",
    "knobSmall": "knob_small@2x.png",
    "grain": "grain_256.png",
}


def b64(p: pathlib.Path) -> str:
    return base64.b64encode(p.read_bytes()).decode("ascii")


def main() -> None:
    data = {
        "fonts": {k: b64(FONTS / v) for k, v in FONT_FILES.items()},
        "images": {k: "data:image/png;base64," + b64(IMAGES / v) for k, v in IMAGE_FILES.items()},
        "wordmark": json.loads((IMAGES / "logo_wordmark.json").read_text(encoding="utf-8")),
    }
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("// generated by tools/assets/embed_prototype.py - do not edit\nwindow.KICK_ASSETS = "
                   + json.dumps(data, separators=(",", ":")) + ";\n", encoding="utf-8")
    print(OUT.relative_to(ROOT), f"{OUT.stat().st_size / 1024:.0f} KB")


if __name__ == "__main__":
    main()
