"""Compile resources/images/logo_wordmark.json into src/ui/WordmarkData.h (static path data).

The wordmark is drawn as vector paths by the NanoVG UI (DESIGN.md §4.4), so it needs no font and
stays crisp at every scale. Each contour is a run of commands:
    0 = moveTo(x, y)   1 = lineTo(x, y)   2 = quadTo(cx, cy, x, y)   3 = close
with coordinates in em units (y down, baseline of "kick" at 0), plus a per-contour hole flag that
maps to nvgPathWinding(NVG_HOLE).

Usage: python tools/assets/wordmark_header.py   (run after tools/assets/logo.py)
"""
from __future__ import annotations

import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parents[2]
SRC = ROOT / "resources" / "images" / "logo_wordmark.json"
OUT = ROOT / "src" / "ui" / "WordmarkData.h"


def main() -> None:
    data = json.loads(SRC.read_text(encoding="utf-8"))
    cmds: list[int] = []
    coords: list[float] = []
    contours: list[tuple[int, int, int]] = []  # (first cmd, cmd count, hole)
    for c in data["contours"]:
        first = len(cmds)
        for cmd in c["cmds"]:
            op = {"M": 0, "L": 1, "Q": 2, "Z": 3}[cmd[0]]
            cmds.append(op)
            coords.extend(float(v) for v in cmd[1:])
        contours.append((first, len(cmds) - first, 1 if c["hole"] else 0))

    def floats(vals: list[float]) -> str:
        out, line = [], []
        for v in vals:
            line.append(f"{v:.5f}f")
            if len(line) == 8:
                out.append("    " + ", ".join(line) + ",")
                line = []
        if line:
            out.append("    " + ", ".join(line) + ",")
        return "\n".join(out)

    def ints(vals: list[int], per: int = 32) -> str:
        return "\n".join("    " + ", ".join(str(v) for v in vals[i:i + per]) + "," for i in range(0, len(vals), per))

    bbox = data["bbox"]
    text = f"""// Generated by tools/assets/wordmark_header.py from resources/images/logo_wordmark.json -- do not edit.
// "kickarse" in Archivo wdth 125 / wght 800 with the duck offsets of DESIGN.md §4.4, as em-unit paths.
#pragma once

#include <cstdint>

namespace kick {{ namespace ui {{ namespace wordmark {{

// op: 0 moveTo(x,y), 1 lineTo(x,y), 2 quadTo(cx,cy,x,y), 3 close
inline constexpr std::uint8_t kOps[] = {{
{ints(cmds)}
}};

inline constexpr float kCoords[] = {{
{floats(coords)}
}};

struct Contour {{ int firstOp; int opCount; bool hole; }};
inline constexpr Contour kContours[] = {{
{chr(10).join(f"    {{{a}, {b}, {'true' if h else 'false'}}}," for a, b, h in contours)}
}};

inline constexpr int   kNumContours = {len(contours)};
inline constexpr float kBBoxMinX = {bbox[0]:.5f}f, kBBoxMinY = {bbox[1]:.5f}f, kBBoxMaxX = {bbox[2]:.5f}f, kBBoxMaxY = {bbox[3]:.5f}f;

}} }} }} // namespace kick::ui::wordmark
"""
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text, encoding="utf-8")
    print(OUT.relative_to(ROOT), f"{len(contours)} contours, {len(cmds)} ops")


if __name__ == "__main__":
    main()
