# Kickarse -- embeds resources/presets/<Category>/*.kkpreset and resources/shapes/<Category>/*.kkshape
# as byte arrays into a generated KickarseFactory.cpp, defining the data declared in
# src/shared/FactoryData.h (kick::factory::kPresets/kPresetCount/kShapes/kShapeCount).
#
# Uses the same file(READ ... HEX) byte-array technique as cmake/GenerateResources.cmake (pure
# CMake, no external tool) rather than raw string literals, so file content never needs escaping
# and can never collide with a string-literal delimiter. Tolerates either resource folder being
# empty or missing entirely (both produce a header with zero real entries plus a sentinel row, so
# the arrays are never zero-sized).
#
# The globs use CONFIGURE_DEPENDS: adding, removing, or editing a .kkpreset/.kkshape file triggers
# a reconfigure (and hence a refresh of the embedded data) before the next build -- no manual
# "regenerate" step.
#
# Usage: kickarse_embed_factory(<out-source-path>)

function(_kickarse_factory_table VAR_PREFIX FILES_DIR GLOB_PATTERN OUT_SOURCE_BODY OUT_ENTRIES OUT_COUNT)
    file(GLOB_RECURSE _files CONFIGURE_DEPENDS "${FILES_DIR}/${GLOB_PATTERN}")
    if(_files)
        list(SORT _files)
    endif()

    set(_source_body "")
    set(_entries "")
    set(_index 0)

    foreach(_f ${_files})
        file(RELATIVE_PATH _rel "${FILES_DIR}" "${_f}")
        get_filename_component(_category "${_rel}" DIRECTORY)
        get_filename_component(_name "${_f}" NAME_WE)

        file(READ "${_f}" _hex HEX)
        string(LENGTH "${_hex}" _hexlen)
        math(EXPR _size "${_hexlen} / 2")
        if(_size GREATER 0)
            string(REGEX REPLACE "(..)" "0x\\1," _bytes "${_hex}")
        else()
            set(_bytes "")
        endif()

        string(APPEND _source_body
            "static const unsigned char ${VAR_PREFIX}Text_${_index}[] = { ${_bytes}0x00 };\n")
        string(APPEND _entries
            "    { \"${_category}\", \"${_name}\", reinterpret_cast<const char*>(${VAR_PREFIX}Text_${_index}) },\n")

        math(EXPR _index "${_index} + 1")
    endforeach()

    set("${OUT_SOURCE_BODY}" "${_source_body}" PARENT_SCOPE)
    set("${OUT_ENTRIES}" "${_entries}" PARENT_SCOPE)
    set("${OUT_COUNT}" "${_index}" PARENT_SCOPE)
endfunction()

function(kickarse_embed_factory OUT_SOURCE)
    set(_presets_dir "${CMAKE_SOURCE_DIR}/resources/presets")
    set(_shapes_dir  "${CMAKE_SOURCE_DIR}/resources/shapes")

    _kickarse_factory_table(kPreset "${_presets_dir}" "*.kkpreset" _presetSrc _presetEntries _presetCount)
    _kickarse_factory_table(kShape  "${_shapes_dir}"  "*.kkshape"  _shapeSrc  _shapeEntries  _shapeCount)

    set(_out [[// Generated by cmake/EmbedFactory.cmake -- do not edit. Re-run cmake to refresh.
// Defines the data declared in src/shared/FactoryData.h from resources/presets/**/*.kkpreset and
// resources/shapes/**/*.kkshape, embedded verbatim (see FactoryData.h for the array layout).
#include "shared/FactoryData.h"

namespace kick {
namespace factory {

]])
    string(APPEND _out "${_presetSrc}")
    string(APPEND _out "const FactoryFile kPresets[] = {\n${_presetEntries}    { \"\", \"\", \"\" },\n};\n")
    string(APPEND _out "const int kPresetCount = ${_presetCount};\n\n")
    string(APPEND _out "${_shapeSrc}")
    string(APPEND _out "const FactoryFile kShapes[] = {\n${_shapeEntries}    { \"\", \"\", \"\" },\n};\n")
    string(APPEND _out "const int kShapeCount = ${_shapeCount};\n\n")
    string(APPEND _out "} // namespace factory\n} // namespace kick\n")

    file(WRITE "${OUT_SOURCE}" "${_out}")
endfunction()
