# Kickarse -- turns resources/fonts/*.ttf and resources/images/*.png into a small C++ table
# (kick::res::kFonts / kick::res::kImages) the UI can load fonts/images from memory with.
# Pure CMake (file(READ ... HEX) + a regex substitution), no Python/res2c.py dependency, and it
# tolerates the source folders being empty or missing entirely -- both produce a header with zero
# entries that still compiles (a sentinel row is always appended so the arrays are never empty).
#
# Usage:
#   kickarse_generate_resources(<out-header> <out-source> <fonts-dir> <images-dir>)
#
# Regenerates whenever CMake reconfigures; the glob uses CONFIGURE_DEPENDS so adding/removing a
# resource file triggers a reconfigure on the next build.

function(_kickarse_res_table VAR_PREFIX FILES_DIR GLOB_PATTERNS OUT_SOURCE_BODY OUT_ENTRIES OUT_COUNT)
    set(_files "")
    foreach(_pattern ${GLOB_PATTERNS})
        file(GLOB _matches CONFIGURE_DEPENDS "${FILES_DIR}/${_pattern}")
        list(APPEND _files ${_matches})
    endforeach()
    if(_files)
        list(SORT _files)
    endif()

    set(_source_body "")
    set(_entries "")
    set(_index 0)

    foreach(_f ${_files})
        get_filename_component(_name "${_f}" NAME_WE)

        file(READ "${_f}" _hex HEX)
        string(LENGTH "${_hex}" _hexlen)
        math(EXPR _size "${_hexlen} / 2")

        if(_size GREATER 0)
            string(REGEX REPLACE "(..)" "0x\\1," _bytes "${_hex}")
        else()
            set(_bytes "")
        endif()

        string(APPEND _source_body
            "static const unsigned char ${VAR_PREFIX}Data_${_index}[] = { ${_bytes}0x00 };\n")
        string(APPEND _entries
            "    { \"${_name}\", ${VAR_PREFIX}Data_${_index}, ${_size} },\n")

        math(EXPR _index "${_index} + 1")
    endforeach()

    set("${OUT_SOURCE_BODY}" "${_source_body}" PARENT_SCOPE)
    set("${OUT_ENTRIES}" "${_entries}" PARENT_SCOPE)
    set("${OUT_COUNT}" "${_index}" PARENT_SCOPE)
endfunction()

function(kickarse_generate_resources OUT_HEADER OUT_SOURCE FONTS_DIR IMAGES_DIR)
    _kickarse_res_table(kFont "${FONTS_DIR}" "*.ttf;*.otf" _fontSrc _fontEntries _fontCount)
    _kickarse_res_table(kImage "${IMAGES_DIR}" "*.png" _imageSrc _imageEntries _imageCount)

    set(_header [[// Generated by cmake/GenerateResources.cmake -- do not edit.
// Fonts from resources/fonts/*.ttf|*.otf, images from resources/images/*.png, embedded as bytes.
#pragma once

#include <cstddef>

namespace kick { namespace res {

struct Resource {
    const char*          name; // file basename, no extension
    const unsigned char* data;
    std::size_t          size;
};

extern const Resource    kFonts[];
extern const std::size_t kFontCount;

extern const Resource    kImages[];
extern const std::size_t kImageCount;

} } // namespace kick::res
]])

    file(WRITE "${OUT_HEADER}" "${_header}")

    set(_source "// Generated by cmake/GenerateResources.cmake -- do not edit.\n")
    string(APPEND _source "#include \"KickarseResources.hpp\"\n\n")
    string(APPEND _source "namespace kick { namespace res {\n\n")
    string(APPEND _source "${_fontSrc}\n")
    string(APPEND _source "const Resource kFonts[] = {\n${_fontEntries}    { nullptr, nullptr, 0 },\n};\n")
    string(APPEND _source "const std::size_t kFontCount = ${_fontCount};\n\n")
    string(APPEND _source "${_imageSrc}\n")
    string(APPEND _source "const Resource kImages[] = {\n${_imageEntries}    { nullptr, nullptr, 0 },\n};\n")
    string(APPEND _source "const std::size_t kImageCount = ${_imageCount};\n\n")
    string(APPEND _source "} } // namespace kick::res\n")

    file(WRITE "${OUT_SOURCE}" "${_source}")

    message(STATUS "Kickarse resources: ${_fontCount} font(s), ${_imageCount} image(s)")
endfunction()
